/* hdf/src/h4config.h  Generated By CMake during the configuration  */

#ifndef H4_CONFIG_H_
#define H4_CONFIG_H_

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef H4_F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#define H4_F77_FUNC(name,NAME) name ## _

/* As F77_FUNC, but for C identifiers containing underscores. */
#define H4_F77_FUNC_(name,NAME) name ## __

/* Define to 1 if your Fortran compiler doesn't accept -c and -o together. */
/* #undef H4_F77_NO_MINUS_C_MINUS_O */

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef H4_FC_DUMMY_MAIN_EQ_F77 */

/* Define to 1 if you have the <arpa/inet.h> header file. */
/* #undef H4_HAVE_ARPA_INET_H */

/* Define to 1 if you have the <fcntl.h> header file. */
#define H4_HAVE_FCNTL_H 1

/* Define to 1 if you have the `fork' function. */
/* #undef H4_HAVE_FORK */

/* Define to 1 if you have the `getrusage' function. */
/* #undef H4_HAVE_GETRUSAGE */

/* Define to 1 if you have the <winsock2.h> header file. */
#define H4_HAVE_WINSOCK2_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef H4_HAVE_INTTYPES_H */

/* Define to 1 if you have the <jpeglib.h> header file. */
#define H4_HAVE_JPEGLIB_H 1

/* Define to 1 if you have the `jpeg' library (-ljpeg). */
#define H4_HAVE_LIBJPEG 1

/* Define to 1 if you have the `sz' library (-lsz). */
#define H4_HAVE_LIBSZ 1

/* Define to 1 if you have the `z' library (-lz). */
#define H4_HAVE_LIBZ 1

/* Define if we export HDF4-built unmangled netCDF 2.3.2 API calls */
/* #undef H4_HAVE_NETCDF */

/* Define to 1 if you have the <netinet/in.h> header file. */
/* #undef H4_HAVE_NETINET_IN_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define H4_HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define H4_HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define H4_HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define H4_HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define H4_HAVE_STRING_H 1

/* Define to 1 if you have the `system' function. */
#define H4_HAVE_SYSTEM 1

/* Define to 1 if you have the <sys/file.h> header file. */
#define H4_HAVE_SYS_FILE_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
/* #undef H4_HAVE_SYS_RESOURCE_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define H4_HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define H4_HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define H4_HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
/* #undef H4_HAVE_SYS_WAIT_H */

/* Define if szip has encoder */
#define H4_HAVE_SZIP_ENCODER 1

/* Define to 1 if you have the <szlib.h> header file. */
#define H4_HAVE_SZLIB_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define H4_HAVE_UNISTD_H 1

/* Define to 1 if you have the `wait' function. */
/* #undef H4_HAVE_WAIT */

/* Define to 1 if you use the WIN32_API. */
#define H4_HAVE_WIN32_API 1

/* Define to 1 if you have the <zlib.h> header file. */
#define H4_HAVE_ZLIB_H 1

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
#define H4_LT_OBJDIR ""

/* Define if deprecated public API symbols are disabled */
/* #undef H4_NO_DEPRECATED_SYMBOLS */

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef H4_NO_MINUS_C_MINUS_O */

/* Name of package */
#define H4_PACKAGE "hdf4"

/* Define to the address where bug reports for this package should be sent. */
#define H4_PACKAGE_BUGREPORT "help@hdfgroup.org"

/* Define to the full name of this package. */
#define H4_PACKAGE_NAME "HDF"

/* Define to the full name and version of this package. */
#define H4_PACKAGE_STRING "HDF 4.3.0"

/* Define to the one symbol short name of this package. */
#define H4_PACKAGE_TARNAME "hdf4"

/* Define to the home page for this package. */
#define H4_PACKAGE_URL "http://www.hdfgroup.org"

/* Define to the version of this package. */
#define H4_PACKAGE_VERSION "4.3.0"

/* The size of `long', as computed by sizeof. */
#define H4_SIZEOF_LONG 4

/* Define to 1 if all of the C90 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define H4_STDC_HEADERS 1

/* Version number of package */
#define H4_VERSION "4.3.0"

/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
   significant byte first (like Motorola and SPARC, unlike Intel). */
/* #undef H4_WORDS_BIGENDIAN */

#endif
